site_name: Apache Mynewt
site_url: http://mynewt.incubator.apache.org

theme_dir: 'custom-theme'

pages:
- Home: 'index.md'
- Documentation: 'documentation.md'
- Download: 'download.md'
- Community: 'community.md'
- Events: 'events.md'
- Apache Mynewt Manual:
    - Introduction: 'os/get_started/introduction.md'
    - Get Started:
        - 'Blinky, The First Project': 'os/get_started/project1.md'
        - 'Understanding Newt Terms': 'os/get_started/vocabulary.md'
    - Tutorials:
        - 'Blinky on Real Hardware': 'os/get_acclimated/project2.md'
        - 'Unit Testing a Package': 'os/get_acclimated/project3.md'
    - Manual:
        - OS Core: 
            - OS Fundamentals: 
                - Overview: 'os/core_os/mynewt_os.md' 
                - Functions:
                    - 'os_init': 'os/core_os/os_init.md'
                    - 'os_start': 'os/core_os/os_start.md'
                    - 'os_started': 'os/core_os/os_started.md'
            - Scheduler: 
                - 'Overview': 'os/core_os/context_switch/context_switch.md'
                - 'Functions':
                    - 'os_sched': 'os/core_os/context_switch/os_sched.md'
                    - 'os_sched_ctx_sw_hook': 'os/core_os/context_switch/os_sched_ctx_sw_hook.md'
                    - 'os_sched_get_current_task': 'os/core_os/context_switch/os_sched_get_current_task.md'
                    - 'os_sched_insert': 'os/core_os/context_switch/os_sched_insert.md'
                    - 'os_sched_next_task': 'os/core_os/context_switch/os_sched_next_task.md'
                    - 'os_sched_os_timer_exp': 'os/core_os/context_switch/os_sched_os_timer_exp.md'
                    - 'os_sched_resort': 'os/core_os/context_switch/os_sched_resort.md'
                    - 'os_sched_set_current_task': 'os/core_os/context_switch/os_sched_set_current_task.md'
                    - 'os_sched_sleep': 'os/core_os/context_switch/os_sched_sleep.md'
                    - 'os_sched_wakeup': 'os/core_os/context_switch/os_sched_wakeup.md'
            - Time: 
                - 'Overview': 'os/core_os/time/time.md'
                - 'Functions':
                    - 'os_time_delay': 'os/core_os/time/os_time_delay.md'
                    - 'os_time_get': 'os/core_os/time/os_time_get.md'
                    - 'os_time_tick': 'os/core_os/time/os_time_tick.md'
            - Tasks: 
                - 'Overview': 'os/core_os/task/task.md'
                - 'Functions': 
                    - 'os_task_count': 'os/core_os/task/os_task_count.md'
                    - 'os_task_info_get_next': 'os/core_os/task/os_task_info_get_next.md'
                    - 'os_task_init': 'os/core_os/task/os_task_init.md'
                    - 'os_task_sanity_checkin': 'os/core_os/task/os_task_sanity_checkin.md'
            - Event Queues: 
                - 'Overview': 'os/core_os/event_queue/event_queue.md'
                - 'Functions':
                    - 'os_eventq_get': 'os/core_os/event_queue/os_eventq_get.md'
                    - 'os_eventq_init': 'os/core_os/event_queue/os_eventq_init.md'
                    - 'os_eventq_put': 'os/core_os/event_queue/os_eventq_put.md'
                    - 'os_eventq_put2': 'os/core_os/event_queue/os_eventq_put2.md'
                    - 'os_eventq_remove': 'os/core_os/event_queue/os_eventq_remove.md'
            - Semaphores: 
                - 'Overview': 'os/core_os/semaphore/semaphore.md'
                - 'Functions':
                    - 'os_sem_delete': 'os/core_os/semaphore/os_sem_delete.md'
                    - 'os_sem_init': 'os/core_os/semaphore/os_sem_init.md'
                    - 'os_sem_pend': 'os/core_os/semaphore/os_sem_pend.md'
                    - 'os_sem_release': 'os/core_os/semaphore/os_sem_release.md'
            - Mutexes: 
                - 'Overview': 'os/core_os/mutex/mutex.md'
                - 'Functions':
                    - 'os_mutex_delete': 'os/core_os/mutex/os_mutex_delete.md'
                    - 'os_mutex_init': 'os/core_os/mutex/os_mutex_pend.md'
                    - 'os_mutex_release': 'os/core_os/mutex/os_mutex_release.md'
            - Memory Pools: 
                - 'Overview': 'os/core_os/memory_pool/memory_pool.md'
                - 'Functions': 
                    - 'os_memblock_get': 'os/core_os/memory_pool/os_memblock_get.md'
                    - 'os_mempool_init': 'os/core_os/memory_pool/os_mempool_init.md'
                    - 'os_memblock_put': 'os/core_os/memory_pool/os_memblock_put.md'
                    - 'OS_MEMPOOL_BYTES': 'os/core_os/memory_pool/OS_MEMPOOL_BYTES.md'
            - Heap: 
                - 'Overview': 'os/core_os/heap/heap.md'
                - 'Functions':
                    - 'os_free': 'os/core_os/heap/os_free.md'
                    - 'os_malloc': 'os/core_os/heap/os_malloc.md'
                    - 'os_realloc': 'os/core_os/heap/os_realloc.md'
            - Mbufs: 
                - 'Overview': 'os/core_os/mbuf/mbuf.md'
                - 'Functions':
                    - 'OS_MBUF_PKTHDR': 'os/core_os/mbuf/OS_MBUF_PKTHDR.md'
                    - 'OS_MBUF_PKTHDR_TO_MBUF': 'os/core_os/mbuf/OS_MBUF_PKTHDR_TO_MBUF.md'
                    - 'OS_MBUF_PKTLEN': 'os/core_os/mbuf/OS_MBUF_PKTLEN.md'
                    - 'OS_MBUF_DATA': 'os/core_os/mbuf/OS_MBUF_DATA.md'
                    - 'OS_MBUF_USRHDR': 'os/core_os/mbuf/OS_MBUF_USRHDR.md'
                    - 'OS_MBUF_USRHDR_LEN': 'os/core_os/mbuf/OS_MBUF_USRHDR_LEN.md'
                    - 'OS_MBUF_LEADINGSPACE': 'os/core_os/mbuf/OS_MBUF_LEADINGSPACE.md'
                    - 'OS_MBUF_TRAILINGSPACE': 'os/core_os/mbuf/OS_MBUF_TRAILINGSPACE.md'
                    - 'os_mbuf_adj': 'os/core_os/mbuf/os_mbuf_adj.md'
                    - 'os_mbuf_append': 'os/core_os/mbuf/os_mbuf_append.md'
                    - 'os_mbuf_concat': 'os/core_os/mbuf/os_mbuf_concat.md'
                    - 'os_mbuf_copydata': 'os/core_os/mbuf/os_mbuf_copydata.md'
                    - 'os_mbuf_copyinto': 'os/core_os/mbuf/os_mbuf_copyinto.md'
                    - 'os_mbuf_dup': 'os/core_os/mbuf/os_mbuf_dup.md'
                    - 'os_mbuf_extend': 'os/core_os/mbuf/os_mbuf_extend.md'
                    - 'os_mbuf_free_chain': 'os/core_os/mbuf/os_mbuf_free_chain.md'
                    - 'os_mbuf_get': 'os/core_os/mbuf/os_mbuf_get.md'
                    - 'os_mbuf_get_pkthdr': 'os/core_os/mbuf/os_mbuf_get_pkthdr.md'
                    - 'os_mbuf_memcmp': 'os/core_os/mbuf/os_mbuf_memcmp.md'
                    - 'os_mbuf_off': 'os/core_os/mbuf/os_mbuf_off.md'
                    - 'os_mbuf_pool_init': 'os/core_os/mbuf/os_mbuf_pool_init.md'
                    - 'os_mbuf_prepend': 'os/core_os/mbuf/os_mbuf_prepend.md'
                    - 'os_mbuf_pullup': 'os/core_os/mbuf/os_mbuf_pullup.md'
                    - 'os_msys_get': 'os/core_os/mbuf/os_msys_get.md'
                    - 'os_msys_get_pkthdr': 'os/core_os/mbuf/os_msys_get_pkthdr.md'
                    - 'os_msys_register': 'os/core_os/mbuf/os_msys_register.md'
                    - 'os_msys_reset': 'os/core_os/mbuf/os_msys_reset.md'
            - Sanity: 
                - 'Overview': 'os/core_os/sanity/sanity.md'
                - 'Functions': 
                    - 'os_sanity_check_init': 'os/core_os/sanity/os_sanity_check_init.md'
                    - 'os_sanity_check_list_lock': 'os/core_os/sanity/os_sanity_check_list_lock.md'
                    - 'os_sanity_check_list_unlock': 'os/core_os/sanity/os_sanity_check_list_unlock.md'
                    - 'os_sanity_check_register': 'os/core_os/sanity/os_sanity_check_register.md'
                    - 'os_sanity_check_reset': 'os/core_os/sanity/os_sanity_check_reset.md'
                    - 'os_sanity_task_init': 'os/core_os/sanity/os_sanity_task_init.md'
            - Callouts: 
                - 'Overview': 'os/core_os/callout/callout.md'
                - 'Functions': 
                    - 'os_callout_func_init': 'os/core_os/callout/os_callout_func_init.md'
                    - 'os_callout_init': 'os/core_os/callout/os_callout_init.md'
                    - 'os_callout_queued': 'os/core_os/callout/os_callout_queued.md'
                    - 'os_callout_reset': 'os/core_os/callout/os_callout_reset.md'
                    - 'os_callout_stop': 'os/core_os/callout/os_callout_stop.md'
            - Porting to other Platforms: 'os/core_os/port_os.md'
        - Console:  
            - 'Overview': 'os/modules/console/console.md'
            - 'Functions':
                - 'console_add_char': 'os/modules/console/console_add_char.md'
                - 'console_blocking_mode': 'os/modules/console/console_blocking_mode.md'
                - 'console_blocking_tx': 'os/modules/console/console_blocking_tx.md'
                - 'console_init': 'os/modules/console/console_init.md'
                - 'console_printf': 'os/modules/console/console_printf.md'
                - 'console_pull_char': 'os/modules/console/console_pull_char.md'
                - 'console_pull_char_head': 'os/modules/console/console_pull_char_head.md'
                - 'console_queue_char': 'os/modules/console/console_queue_char.md'
                - 'console_read': 'os/modules/console/console_read.md'
                - 'console_rx_char': 'os/modules/console/console_rx_char.md'
                - 'console_tx_char': 'os/modules/console/console_tx_char.md'
                - 'console_write': 'os/modules/console/console_write.md'
        - Shell: 
            - 'Overview': 'os/modules/shell/shell.md'
            - 'Functions': 
                - 'shell_cmd': 'os/modules/shell/shell_cmd.md'
                - 'shell_cmd_list_lock': 'os/modules/shell/shell_cmd_list_lock.md'
                - 'shell_cmd_list_unlock': 'os/modules/shell/shell_cmd_list_unlock.md'
                - 'shell_cmd_register': 'os/modules/shell/shell_cmd_register.md'
                - 'shell_console_rx_cb': 'os/modules/shell/shell_console_rx_cb.md'
                - 'shell_echo_cmd': 'os/modules/shell/shell_echo_cmd.md'
                - 'shell_help_cmd': 'os/modules/shell/shell_help_cmd.md'
                - 'shell_nlip_input_register': 'os/modules/shell/shell_nlip_input_register.md'
                - 'shell_nlip_mqueue_process': 'os/modules/shell/shell_nlip_mqueue_process.md'
                - 'shell_nlip_mtx': 'os/modules/shell/shell_nlip_mtx.md'
                - 'shell_nlip_output': 'os/modules/shell/shell_nlip_output.md'
                - 'shell_nlip_process': 'os/modules/shell/shell_nlip_process.md'
                - 'shell_os_mpool_display_cmd': 'os/modules/shell/shell_os_mpool_display_cmd.md'
                - 'shell_os_tasks_display_cmd': 'os/modules/shell/shell_os_tasks_display_cmd.md'
                - 'shell_process_command': 'os/modules/shell/shell_process_command.md'
                - 'shell_read_console': 'os/modules/shell/shell_read_console.md'
                - 'shell_task_func': 'os/modules/shell/shell_task_func.md'
                - 'shell_task_init': 'os/modules/shell/shell_task_init.md'
        - Bootloader: 
            - 'Overview': 'os/modules/bootloader/bootloader.md'
            - 'Functions':
                - 'boot_build_status': 'os/modules/bootloader/boot_build_status.md'
                - 'boot_build_status_one': 'os/modules/bootloader/boot_build_status_one.md'
                - 'boot_clear_status': 'os/modules/bootloader/boot_clear_status.md'
                - 'boot_copy_area': 'os/modules/bootloader/boot_copy_area.md'
                - 'boot_copy_image': 'os/modules/bootloader/boot_copy_image.md'
                - 'boot_erase_area': 'os/modules/bootloader/boot_erase_area.md'
                - 'boot_fill_slot': 'os/modules/bootloader/boot_fill_slot.md'
                - 'boot_find_image_area_idx': 'os/modules/bootloader/boot_find_image_area_idx.md'
                - 'boot_find_image_part': 'os/modules/bootloader/boot_find_image_part.md'
                - 'boot_find_image_slot': 'os/modules/bootloader/boot_find_image_slot.md'
                - 'boot_go': 'os/modules/bootloader/boot_go.md'
                - 'boot_init_flash': 'os/modules/bootloader/boot_init_flash.md'
                - 'boot_move_area': 'os/modules/bootloader/boot_move_area.md'
                - 'boot_read_image_header': 'os/modules/bootloader/boot_read_image_header.md'
                - 'boot_read_image_headers': 'os/modules/bootloader/boot_read_image_headers.md'
                - 'boot_read_status': 'os/modules/bootloader/boot_read_status.md'
                - 'boot_select_image_slot': 'os/modules/bootloader/boot_select_image_slot.md'
                - 'boot_slot_addr': 'os/modules/bootloader/boot_slot_addr.md'
                - 'boot_slot_to_area_idx': 'os/modules/bootloader/boot_slot_to_area_idx.md'
                - 'boot_swap_areas': 'os/modules/bootloader/boot_swap_areas.md'
                - 'boot_vect_delete_main': 'os/modules/bootloader/boot_vect_delete_main.md'
                - 'boot_vect_delete_test': 'os/modules/bootloader/boot_vect_delete_test.md'
                - 'boot_vect_read_main': 'os/modules/bootloader/boot_vect_read_main.md'
                - 'boot_vect_read_one': 'os/modules/bootloader/boot_vect_read_one.md'
                - 'boot_vect_read_test': 'os/modules/bootloader/boot_vect_read_test.md'
                - 'boot_write_status': 'os/modules/bootloader/boot_write_status.md'
        - 'File System Abstraction': 'os/modules/filesystem.md'
        - 'Newtron Flash File System': 'os/modules/nffs.md'
        - Test Utilities:
            - 'Overview': 'os/modules/testutil/testutil.md'
            - 'Functions':  
                - 'tu_case_abort': 'os/modules/testutil/tu_case_abort.md'
                - 'tu_case_append_assert_msg': 'os/modules/testutil/tu_case_append_assert_msg.md'
                - 'tu_case_append_buf': 'os/modules/testutil/tu_case_append_buf.md'
                - 'tu_case_append_file_info': 'os/modules/testutil/tu_case_append_file_info.md'
                - 'tu_case_append_manual_pass_msg': 'os/modules/testutil/tu_case_append_manual_pass_msg.md'
                - 'tu_case_complete': 'os/modules/testutil/tu_case_complete.md'
                - 'tu_case_fail_assert': 'os/modules/testutil/tu_case_fail_assert.md'
                - 'tu_case_init': 'os/modules/testutil/tu_case_init.md'
                - 'tu_case_pass_manual': 'os/modules/testutil/tu_case_pass_manual.md'
                - 'tu_case_set_name': 'os/modules/testutil/tu_case_set_name.md'
                - 'tu_case_vappend_buf': 'os/modules/testutil/tu_case_vappend_buf.md'
                - 'tu_case_write_fail_buf': 'os/modules/testutil/tu_case_write_fail_buf.md'
                - 'tu_case_write_pass_auto': 'os/modules/testutil/tu_case_write_pass_auto.md'
                - 'tu_case_write_pass_buf': 'os/modules/testutil/tu_case_write_pass_buf.md'
                - 'tu_init': 'os/modules/testutil/tu_init.md'
                - 'tu_restart': 'os/modules/testutil/tu_restart.md'
                - 'tu_suite_init': 'os/modules/testutil/tu_suite_init.md'
                - 'tu_suite_set_name': 'os/modules/testutil/tu_suite_set_name.md'
        - Image Manager:
            - 'Overview': 'os/modules/imgmgr/imgmgr.md'
            - 'Functions': 
                - 'imgmgr_module_init': 'os/modules/imgmgr/imgmgr_module_init.md'
                - 'imgr_ver_parse': 'os/modules/imgmgr/imgr_ver_parse.md'
                - 'imgr_ver_str': 'os/modules/imgmgr/imgr_ver_str.md'
        - 'Baselibc library': 'os/modules/baselibc.md'
        - Embedded Lua:
            - 'Overview': 'os/modules/elua/elua.md'
            - 'Functions':
                - 'lua_init': 'os/modules/elua/lua_init.md'
                - 'lua_main': 'os/modules/elua/lua_main.md'
        - JSON: 
            - 'Overview': 'os/modules/json/json.md'
            - 'Functions':
                - 'json_encode_object_entry': 'os/modules/json/json_encode_object_entry.md'
                - 'json_encode_object_finish': 'os/modules/json/json_encode_object_finish.md'
                - 'json_encode_object_key': 'os/modules/json/json_encode_object_key.md'
                - 'json_encode_object_start': 'os/modules/json/json_encode_object_start.md'
                - 'json_encode_value': 'os/modules/json/json_encode_value.md'
                - 'json_internal_read_object': 'os/modules/json/json_internal_read_object.md'
                - 'json_read_array': 'os/modules/json/json_read_array.md'
                - 'json_read_object': 'os/modules/json/json_read_object.md'
                - 'json_target_address': 'os/modules/json/json_target_address.md'
- Newt Tool Manual:
    - Introduction: 'newt/newt_intro.md'
    - Tutorials:
        - 'Install newt from source on Mac': 'newt/newt_mac.md'
        - 'Install newt from source on Linux': 'newt/newt_linux.md'
    - Manual:
        - 'Command structure': 'newt/newt_ops.md'
        - 'Command list': 
            - 'newt app': 'newt/command_list/newt_app.md'
            - 'newt help': 'newt/command_list/newt_help.md'
            - 'newt new': 'newt/command_list/newt_new.md'
            - 'newt pkg': 'newt/command_list/newt_pkg.md'
            - 'newt target': 'newt/command_list/newt_target.md'
            - 'newt version': 'newt/command_list/newt_version.md'
        - 'Creating Packages': 'newt/packaging/dist.md'
- Newt Manager Manual:
    - 'Introduction': 'newtmgr/overview.md'
    - Tutorials:
        - 'Project Slinky': 'newtmgr/project-slinky.md'
    - Manual:
        - 'Protocol': 'newtmgr/protocol.md'

markdown_extensions:
    - toc:
        permalink: true
    - sane_lists

extra:
    chapters:
        Chapter 1 - Get Started: 'The chapter organization is outlined below. Each chapter will include one or more tutorials for hands-on experience with the material in each chapter.'
        Chapter 2 - Get Acclimated: 'Delves deeper into the concepts crucial to the software development effort.'
        Chapter 3 - Newt Tool: 'Describes the command structure and details all the available commands to help you with your project.'
        Chapter 4 - Mynewt OS: 'Provides an overview of the features available and how to customize for your hardware and software application.'
        Chapter 5 - Modules: 'Lays out all the available modules such as HAL (Hardware Abstraction Layer), console, le system, networking stacks, and other middleware components.'
        Chapter 6 - Packaging it: 'Packages for distribution delineates the process of creating complete packages to load on your embedded device to get it up, connected, and ready for remote management.'
    events:
        event 1:
            title: 'See us at Bluetooth World!'
            description: 'Find out more about our open-source offering at this event featuring the best of IoT innovations powered by Bluetooth'
            location: "Levi's Stadium, CA, USA"
            date: 'March 15 - 16, 2016'
        event 2:
            title: 'Internet of Things World'
            description: 'Check out our product at the largest and most comprehensive IoT event on the market.'
            location: "Moscone Center, San Francisco, CA, USA"
            date: 'May 10 - 12, 2016'

copyright: 'Copyright &copy; 2015 The Apache Software Foundation, Licensed under the Apache License, Version 2.0 Apache and the Apache feather logo are trademarks of The Apache Software Foundation.<br>The Apache Software Foundation Apache Incubator'

google_analytics: ['UA-72162311-1', 'mynewt.incubator.apache.org']
