site_name: MyNewt

pages:
- Home: index.md
- Getting Started:
    - 'Introduction': 'chapter1/intro.md'
    - 'Newt Concepts': 'chapter1/newt_concepts.md'
    - 'Blinkie, The First Project': 'chapter1/project1.md'
- Getting Acclimatized:
    - 'Understanding Newt Terms': 'chapter2/vocabulary.md'
    - 'Project 2': 'chapter2/project2.md'
    - 'Project 3': 'chapter2/project3.md'
- Newt tool Reference:
    - 'Command structure': 'chapter3/newt_ops.md'
    - 'Command list': 'chapter3/newt_tool_reference.md'

theme: mkdocs
