site_name: Apache Mynewt
site_url: http://mynewt.apache.org
repo_url: https://github.com/apache/mynewt-site/
edit_uri: blob/master/docs
site_favicon: /img/mynewt-logo-only-newt32x32.png

theme_dir: 'custom-theme'

pages:
- Home: 'index.md'
- Pages:
    - Bluetooth Low Energy 4.2: 'pages/ble.md'
    - Security Lifecycle: 'pages/securitybullets.md'
- Quick Start: 'quick-start.md'
- About: 'about.md'
- Talks: 'talks.md'
- Download: 'download.md'
- Community: 'community.md'
- Events: 'events.md'
- Documentation: 'documentation.md'

markdown_extensions:
    - toc:
        permalink: False
    - sane_lists
    - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        pygments_style: xcode

extra:
    version: 'v1_4_0'
    versions:
        - label: 'master'
          dir: 'master'
          latest: True,
          separate: True
        - label: '0.9.0'
          dir: 'v0_9_0'
          latest: False
        - label: '1.0.0'
          dir: 'v1_0_0'
          latest: False
        - label: '1.1.0'
          dir: 'v1_1_0'
          latest: False
        - label: '1.2.0'
          dir: 'v1_2_0'
          latest: False
        - label: '1.3.0'
          dir: 'v1_3_0'
          latest: False
        - label: '1.4.0'
          dir: 'v1_4_0'
          latest: False
    doc_path: 'latest'
    events:
        event 1:
            title: '<a href="http://events.linuxfoundation.org/events/embedded-linux-conference">Embedded Linux Conference 2018</a>'
            description: 'Topics to be announced soon'
            location: "Hilton Portland Downtown, Portland, OR, USA"
            date: '12-14 March, 2018'

copyright: 'Apache Mynewt is available under Apache License, version 2.0.'

google_analytics: ['UA-72162311-1', 'auto']
